name: Desplegament Vue.js a EC2 (Dev i Prod)

# 1. QUAN S'EXECUTA AQUEST WORKFLOW?
on:
  push:
    branches:
      - main # Quan fem push o merge a la branca de producció
      - develop # Quan fem push o merge a la branca de desenvolupament

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # DEFINICIÓ DE VARIABLES D'ENTORN DINÀMIQUES MIG "INVENT" PER PODER USAR EL MATEIX WORKFLOW PER A DEV I PROD
    # Ací fem la "màgia" per decidir host, username i key segons la branca actual
    env:
      # Ternària: Si la branca és 'main', usa el host de PROD; si no, el de DEV
      CURRENT_HOST: ${{ github.ref == 'refs/heads/main' && secrets.PROD_SERVER_HOST || secrets.DEV_SERVER_HOST }}
      CURRENT_USERNAME: ${{ github.ref == 'refs/heads/main' && secrets.PROD_SERVER_USER || secrets.DEV_SERVER_USER }}
      CURRENT_SSH_KEY: ${{ github.ref == 'refs/heads/main' && secrets.PROD_SERVER_SSH_KEY || secrets.DEV_SERVER_SSH_KEY }}

    steps:
      # Pas 1: Descarregar el codi del nostre repositori a la màquina virtual de GitHub
      - name: 📥 Descarregar el codi del repositori
        uses: actions/checkout@v4

      # Pas 2: Preparar l'eina Node.js (necessària per compilar Vue)
      - name: ⚙️ Configurar l'entorn de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Pas 3: Instal·lar totes les llibreries que necessita el projecte de forma neta
      - name: 📦 Instal·lar dependències del projecte
        run: npm ci

      # Pas 4: Convertir el codi Vue en web estàndard (Genera la carpeta 'dist')
      - name: 🏗️ Compilar l'aplicació Vue.js
        run: npm run build

      # Pas 5: Enviar la carpeta 'dist' al nostre servidor EC2
      - name: 🚀 Enviar els fitxers compilats al servidor
        uses: appleboy/scp-action@v0.1.4
        with:
          # LA MÀGIA CONDICIONAL:
          # La sintaxi és: ${{ condició && 'valor_si_és_cert' || 'valor_si_és_fals' }}
          # Si estem a la branca 'main', agafa el secret PROD. Si no, agafa el secret DEV.
          host: ${{ env.CURRENT_HOST }}
          username: ${{ env.CURRENT_USERNAME }}
          key: ${{ env.CURRENT_SSH_KEY }}

          # Què enviem i on ho enviem?
          source: "dist/*"
          target: "/var/www/frontend/dist" # La ruta és exactament la mateixa als dos servidors

          # Eliminem la carpeta arrel 'dist/' perquè els fitxers quedin directament a destí
          strip_components: 1
